---
title: "Project 2"
authors: "Luke Abbatessa, Jacob Alltucker, Lillian Ein"
output: html_document
---

Instructions
------------

Please follow the instructions below to complete your assignment:

1. Open the R markdown template **biostatistics-projTemplate.Rmd** in RStudio
2. Insert the relevant information (i.e., assignment number, student name)
3. Save the file as **projNUMBER-yourLastName.Rmd** replacing **NUMBER** with the assignment \#
4. Your answers should consist of the R code used to generate the results and their interpretation
5. Do not use any special symbols such as \%, \#, \$, and \& in your answers
6. Generate an HTML version of the Markdown document by clicking on the **Knit** icon in RStudio
7. Submit your RMD project file via the Turnitin link in the Assignment section of Blackboard and email
    a copy of your RMD and HTML project files to your TA

Problem 1
---------
```{r}
d1 <- read.csv(file = "http://faraway.neu.edu/biostats/assn2_dataset1.csv",
as.is = FALSE)
```

### Question 1

```{r}
d1.2000 <- subset(d1, subset = year == "2000")
d1.2003 <- subset(d1, subset = year == "2003")

unique.data <- unique(d1$speciesID)

matrix.spec.data <- matrix(nrow = length(unique.data), ncol = 2)

for (i in 1:length(unique.data)) {
  spec.2000 <- subset(d1.2000, subset = speciesID == unique.data[i])
  spec.2003 <- subset(d1.2003, subset = speciesID == unique.data[i])
matrix.spec.data[i, ] <- c(weighted.mean(spec.2000$lat, spec.2000$abundance), weighted.mean(spec.2003$lat, spec.2003$abundance))
}
matrix.spec.data

results <- data.frame(speciesID = unique.data, moveDist = matrix.spec.data[, 2] - matrix.spec.data[, 1])
new.results <- na.omit(results)
new.results
```

### Question 2

```{r}
new.results$moveDistSign <- ifelse(new.results$moveDist > 0, 1, 0)
new.results$moveDistSign <- ifelse(new.results$moveDist < 0, 0, new.results$moveDistSign)
new.results

# In this context, while a positive value is representative of a shift northward for the "center of gravity" of the geographical distribution of each intertidal species, a negative value is representative of a shift southward. 
```

### Question 3

```{r}
species.north <- 0
species.south <- 0
for (i in 1:length(new.results$moveDistSign)) {
  if(new.results$moveDistSign[i] == 1) {
    species.north = species.north + 1
  }else if(new.results$moveDistSign[i] == 0) {
    species.south = species.south + 1
  }

}
species.north
species.south

bp <- barplot(c(species.north, species.south), ylim = c(0,35), names = c("Species that Moved Northward", "Species that Moved Southward"), ylab = "Number of Species", main = "Number of Species that Moved Northward vs. Southward")

# Based on this figure, I do not think that there is evidence of a northward shift in the distribution of intertidal species. This is supported by the fact that, out of the 57 unique species, 31 have moved southward and 26 have moved northward; in other words, since more species have moved southward than northward, one can say there is actually a shift southward in the distribution of intertidal species.  
```

### Question 4

```{r}
# The appropriate statistical test for our hypothesis is a binomial test, since we're interested in comparing the proportion p of "successes" (the proportion of intertidal species that have shifted northward) from n trials (the total number of intertidal species) to a null expectation p0 (one half of the intertidal species have shifted northward).

# H0: proportion of "successes" in the population is p0 (i.e. p = p0 = 1/2)
# Ha: proportion of "successes" in the population is not p0 (i.e. p not= p0 = 1/2)

binom.test(x = species.north, n = species.north + species.south)

# Since the p-value (0.5966) is not less than 0.05, we fail to reject the null hypothesis, and we can say that the proportion of "successes" in the population is not p0. In other words, the proportion of intertidal species that have shifted northward is different from the null expectation of 50%. 
```

Problem 2
---------
### Question 1

```{r}
df.ID.dev <- unique(subset(d1, select = c("speciesID", "development")))
df3 <- merge(new.results, df.ID.dev)

oldvalues<- c("1", "0")
newvalues <- factor(c("North", "South"))
df3$moveDistSign <- newvalues[match(df3$moveDistSign, oldvalues)]
df3 <- subset(df3, select = -moveDist)
df3
```

### Question 2

```{r}
table.north.south <- table(df3$development, df3$moveDistSign)
new.table.north.south <- table.north.south[2:4, ]
new.table.north.south

bp.2 <- barplot(new.table.north.south, beside = TRUE, ylim = c(0,20), names = c("Species that Moved Northward", "Species that Moved Southward"), ylab = "Number of Species", main = "Species that Moved Northward vs. Southward Per Dispersal Ability", col = c("red", "purple", "blue", "red", "purple", "blue"))
legend("topright", legend = c("Nonplank", "Plankfeed", "Planknonfeed"), fill = c("red", "purple", "blue"))

# Based on the bar graph for species that moved northward, there appears to be no strong relationship between northward movement and dispersal. To support this, the bar graph shows no difference between the number of species that are feeding planktonic (farthest dispersal) and those that are non-planktonic (least dispersal). 
```

### Question 3

```{r}
# The test we should use to assess whether dispersal ability is related to northward movement of intertidal species is a contingency analysis. This is because this test is performed to determine whether two categorical variables, north and south movement, are independent and therefore related or not. This test also assumes that no more than 20% of groups have expected counts less than five and no group have expected counts less than or equal to one. These assumptions fit our data so we are able to execute the contingency analysis. 
```

### Question 4

```{r}
# null hypothesis: northward movement and dispersal ability are independent and not related
# alternate hypothesis: northward movement and dispersal ability are dependent and are related

chi.matrix <- matrix(c(10, 12, 9, 15, 7, 15), nrow = 3, ncol = 2, byrow = TRUE)
rownames(chi.matrix) <- c("Nonplank", "Plankfeed", "Planknonfeed")
colnames(chi.matrix) <- c("North", "South")
         
chisq.test(chi.matrix)

# Since the p-value of 0.6458 is above the critical value of 0.05, we cannot reject the null hypothesis. Therefore we can conclude that dispersal ability is not related to northward movement of intertidal species.
```

Problem 3
---------
```{r}
#Download d2
d2 <- read.csv(file = "http://faraway.neu.edu/biostats/assn2_dataset2.csv")
```

### Question 1

```{r}
# The best test to conduct in this situation would be a Chi-squared goodness of fit test. The chi-squared goodness of fit test can be used to determine if data comes from a specific, discrete probability distribution. This can be applied to the Poisson distribution, where the test can be used to determine whether or not the data comes from that distribution. It follows from the definition of the Poisson distribution that it will also allow us to determine if the data is spatially and temporally independent.
```

### Question 2

```{r}
# H0: The data comes from a Poisson distribution and are spatially and temporally independent.
# Ha: The data does not come from a Poisson distribution and instead comes from a different distribution.
```

### Question 3

```{r}
# The assumptions of this test are as follows:
# No more than 20% of the classes can have an expected count less than 5.
# No class can have an expected count less than or equal to one.
```

### Question 4

```{r}
# conducting a Chi-squared test
sum(d2$number.species)

# calculate lambda
lambda.d2 <- weighted.mean(x = d2$migration.distance, w = d2$number.species)

# lambda of 1.05
# Calculate expected probability distribution, P(c)
c <- 0:5
d2.exp <- dpois(c, lambda.d2)
d2.exp
# ensure that probabilities sum up to 1
sum(dpois(c, lambda.d2))
(exp(-lambda.d2)*lambda.d2^c)/factorial(c)
# they do not sum up, so we need to create a class >5
d2.poisson <- c(dpois(c, lambda.d2), 1 - sum(dpois(c, lambda.d2)))

# Expected vs observed counts

d2.counts <- data.frame(Class = c(0:5, ">5"), Observed = c(d2$number.species, '>5' = 0), Expected = d2.poisson * sum(d2$number.species))

# combine classes 4 through 6 into >4 category to abide by assumption of no class expected count <= 1
d2.comb <- d2.counts[1:5, ]
d2.comb[5, 2:3] <- d2.comb[5, 2:3] + d2.counts[6, 2:3] + d2.counts[7, 2:3]
# observed chi-squared
chisq.obs <- sum((d2.comb$Observed - d2.comb$Expected)^2/d2.comb$Expected)
# DF = N - k - 1, so 5-1-1 = 3
pchisq(q = chisq.obs, df = 3, lower.tail = FALSE)

# Conclusion: Because the p-value of 0.6596463 is greater than our critical value of 0.05, we therefore fail to reject H0. This indicates that the data does in fact come from a Poisson distribution.

```

### Question 5

```{r}
bp.obs <- barplot(d2.comb$Observed, ylim = c(0,35), names = 0:4, ylab = "Species Number", xlab = "Distance Migrated", main = "Species Number vs. Distance Migrated")
points(bp.obs, d2.comb$Expected, col = "red")

# This distribution suggests that most species are likely not going to be able to migrate sufficiently to escape climate change. The majority of species can are either sedentary or can only migrate 1 or 2 km a year(and according to 6, this would be insufficient to evade the northward expansion of climate conditions at 2.4 km/year)
```

### Question 6

```{r}
d3 <- read.csv(file = "http://faraway.neu.edu/biostats/assn2_dataset3.csv")
#subset east and west and determine if data is normal

d3.east <- subset(d3, subset = coast == "East")

hist(d3.east$migration)

qqnorm(d3.east$migration)
qqline(d3.east$migration)

shapiro.test(d3.east$migration)

d3.west <- subset(d3, subset = coast == "West")

hist(d3.west$migration)

qqnorm(d3.west$migration)
qqline(d3.west$migration)

shapiro.test(d3.west$migration)

# data appears that distribution on the east and west coasts are normal

# For this question, the best test to use would be a one sample t-test. A one-sample t-test allows determination of whether a population mean differs from a specific value. This is the perfect test for this situation, as we need to compare the migration distance of species (on the East and West coast separately) to the pace of climate change's northward movement (aka its yearly migration north). We also know that the data set is normally distributed, and we are going to assume that the sample is random.
```

### Question 7

```{r}
# Ho: The mean migration rate of the species on the coast of interest (East and West in two separate tests) is equal to the rate that climate conditions migrate (or the pace of the environment). Mu = Mu null

# Ha: The mean migration rate of the the species on the coast of interest (East and West in two separate tests) differs from the annual rate that climate conditions migrate.
```

### Question 8

```{r}
t.test(d3.west$migration, mu = 2.4)

# The p-value of 0.04437 is less than the alpha of 0.05. This means that we can reject Ho, and accept Ha. This indicates that the mean species migration rate on the West coast is greater than the pace of the environment (and its northward migration rate). 

t.test(d3.east$migration, mu = 2.4)

# The p-value of 0.6287 is greater than the alpha of 0.05, meaning that we cannot reject Ho. This indicates that the population mean rate of species migration on the East coast does not differ from the pace of the environment (and its northwards migration rate).
```

### Question 9

```{r}
# means and SE
migration.means <-aggregate(migration ~ coast, data = d3, FUN = mean)
SE <- function(x){sd(x)/sqrt(length(x))}
migration.SE <- aggregate(migration ~ coast, data = d3, FUN = SE)

# upper and lower confidence intervals
upper.mig <- migration.means$migration + 1.96*migration.SE$migration
lower.mig <- migration.means$migration - 1.96*migration.SE$migration

# Barplot
bp.d3 <- barplot(migration.means$migration, ylim = c(0,10), names = c("East Coast","West Coast"), ylab = "Migration Rate", main = "Mean Migration Rate")
arrows(x0 = bp.d3, x1 = bp.d3, y0 = lower.mig, y1 = upper.mig, angle = 90, code = 3, length = 0.1)
abline(a = 2.4, b = 0, lty = 2, col = "red")

# This bar plot suggests that the mean rates of migration between the East coast and the West coast are not statistically different, as the 95% confidence intervals overlap. The 95% percent confidence intervals also recapitulate what we saw in the t-tests to compare to the rate of environmental change (red dashed line), with the West coast barely having statistical significant difference.
```
