---
title: "Project 1"
authors: "Luke Abbatessa, Jacob Alltucker, Lillian Ein"

output: html_document
---

Instructions
------------

Please follow the instructions below to complete your assignment:

1. Open the R markdown template **biostatistics-projTemplate.Rmd** in RStudio
2. Insert the relevant information (i.e., assignment number, student name)
3. Save the file as **projNUMBER-yourLastName.Rmd** replacing **NUMBER** with the assignment \#
4. Your answers should consist of the R code used to generate the results and their interpretation
5. Do not use any special symbols such as \%, \#, \$, and \& in your answers
6. Generate an HTML version of the Markdown document by clicking on the **Knit** icon in RStudio
7. Submit your RMD project file via the Turnitin link in the Assignment section of Blackboard and email
    a copy of your RMD and HTML project files to your TA

Problem 1
---------
### Question 1

```{r}
p.D.F2 <- 0.7
p.F2 <- c(0.2, 0.4, 0.6, 0.8)
p.D.not.F2 <- seq(0.01, 0.5, length = 100)
p.F2.D <- matrix(nrow = length(p.F2), ncol = length(p.D.not.F2))
for (i in 1:length(p.D.not.F2)) {
  p.F2.D[, i] <- (p.F2*p.D.F2)/(((1 - p.F2)*p.D.not.F2[i]) + (p.F2*p.D.F2))
}
```

### Question 2

```{r}
plot(p.D.not.F2, p.F2.D[1,], col = "red", type = "l", xlab = "False Detection Rates", ylab = "Probability of Swine Flu Given Detection", main = "p.F2.D vs. p.D.not.F2", ylim = c(0, 1))
points(p.D.not.F2, p.F2.D[2,], col = "blue", type = "l")
points(p.D.not.F2, p.F2.D[3,], col = "green", type = "l")
points(p.D.not.F2, p.F2.D[4,], col = "orange", type = "l")
legend(x = "topright", legend = c("0.2", "0.4", "0.6", "0.8"), col = c("red", "blue", "green", "orange"), pch = "0")
abline(a = 0.5, b = 0, lty = 2)
```

### Question 3

```{r}
# Regarding the effect of the false detection rate on the probability of swine flu given detection, the figure suggests that, generally speaking, the higher the false detection rate, the lower the probability of swine flu given detection. This effect is most pronounced for the lowest swine flu prevalence of 0.2, and it is the least pronounced for the highest swine flu prevalence of 0.8, which only furthers this relationship. Overall, swine flu prevalence mitigates the effect of the false detection rate on the probability of swine flu given detection. This relationship can be compared to inferential statistics, whereby false detection rate is representative of Type I error (a false positive) and probability of swine flu given detection is representative of a true positive. Just as these two metrics have an inverse relationship, the same goes for false detection rate and the probability of swine flu given detection.
```

### Question 4

```{r}
# Regarding the effectiveness of the detection protocol for swine flu, from a clinical perspective, this figure suggests that the protocol isn't very accurate. To explain, the 60% and 80% swine flu prevalence rates don't even get picked up by the protocol, which says that the protocol is ineffective when more people have it. Looking at the 20% and 40% swine flu prevalence rates, specifically at a false detection rate of 0.3, for example, the probabiliies of swine flu given detection are around 60% and 40%, respectively. Although the procotol seems somewhat effective for thr former, that effectiveness drops considerably for the latter, further dubbing the test as flawed.
```

### Question 5

```{r}
p.F1.V1 <- 0.05
p.F2.V1 <- 0.4
p.F2.V2 <- 0.05
p.F1.V2 <- c(0.2, 0.4, 0.6, 0.8)
p.V1 <- seq(0.001, 1, length = 100)
p.F1.F2 <- matrix(nrow = length(p.F1.V2), ncol = length(p.V1))
for (i in 1:length(p.V1)) {
  p.F1.F2[, i] <- (p.F1.V1*p.V1[i] + p.F1.V2*(1 - p.V1[i])) + (p.F2.V1*p.V1[i] + p.F2.V2*(1-p.V1[i]))
}
```

### Question 6

```{r}
plot(p.V1, p.F1.F2[1,], col = "red", type = "l", xlab = "Proportion of the Standard Vaccine", ylab = "Total Prevalence of Flu Strains", main = "p.F1.V2 vs. p.V1", ylim = c(0, 1))
points(p.V1, p.F1.F2[2,], col = "blue", type = "l")
points(p.V1, p.F1.F2[3,], col = "green", type = "l")
points(p.V1, p.F1.F2[4,], col = "orange", type = "l")
legend(x = "topright", legend = c("0.2", "0.4", "0.6", "0.8"), col = c("red", "blue", "green", "orange"), pch = "0")
```

### Question 7

```{r}

```

Problem 2
---------
### Question 1

```{r}
d1 <- read.csv(file = "http://faraway.neu.edu/biostats/assn1_dataset1.csv")
# Null hypothesis: There is no association between the prevalence of the swine flu and age.
# Alternate hypothesis: There is an association between the prevalence of the swine flu and age.
```

### Question 2

```{r}
aggregate(age ~ flu, FUN = mean, data = d1)
aggregate(age ~ flu, FUN = function(x) {
max(x) - min(x)  
}, data = d1)
# For the mean, the information suggests there is a small discrepancy in the age range of individuals regarding each type of flu, whereas, for the range, the information suggests there is a large discrepancy in the age range of individuals regarding each type of flu. 
```

### Question 3

```{r}
par(mfrow = c(2, 1))
d1.flu.seasonal <- subset(d1, subset = flu == "seasonal")
d1.flu.swine <- subset(d1, subset = flu == "swine")
hist(d1.flu.seasonal$age, ylab = "Frequency", col = "red", xlim = c(0, 90), xlab = "Age", main = "Age Range of Individuals with Seasonal Flu", breaks = 30)
hist(d1.flu.swine$age, ylab = "Frequency", col = "blue", xlim = c(0, 90), xlab = "Age", main = "Age Range of Individuals with Swine Flu", breaks = 30)
```

### Question 4

```{r}
# No, the two strains of the flu do no appear to target the same portion of the population. The seasonal flu only appears to target children, teenagers, the elderly, and the extreme elderly, whereas the swine flu appears to target everyone from teenagers to the elderly, excluding children and the extreme elderly.
```

### Question 5

```{r}
d1.range.swine <- subset(d1.flu.swine, subset = age >= 18 & age <= 65)
age.range.total.swine <- aggregate(age ~ flu, FUN = length, data = d1.range.swine)

d1.range.seasonal <- subset(d1.flu.seasonal, subset = age >= 18 & age <= 65)
age.range.total.seasonal <- aggregate(age ~ flu, FUN = length, data = d1.range.seasonal)

d1.not.range.swine <- subset(d1.flu.swine, subset = age < 18 | age > 65)
age.not.range.total.swine <- aggregate(age ~ flu, FUN = length, data = d1.not.range.swine)

d1.not.range.seasonal <- subset(d1.flu.seasonal, subset = age < 18 | age > 65)
age.not.range.total.seasonal <- aggregate(age ~ flu, FUN = length, data = d1.not.range.seasonal)

d.total <- data.frame("adults" = c(age.range.total.swine$age, age.range.total.seasonal$age), "children and elderly" = c(age.not.range.total.swine$age, age.not.range.total.seasonal$age), row.names = c("swine", "seasonal")
)
d.total
```

### Question 6

```{r}
mosaicplot(d.total, main = "mosaic")

#This supports they hypothesis that there is a association between swine flu prevalence and age. Based on the graphic, swine flu appears to prevalent almost completely in adults compared to children and the elderly. Vice appears to apply for the seasonal flu
```

### Question 7

```{r}
chisq.test(d.total, correct = FALSE)

# This p value is significantly smaller than the critical value of 0.05 and therefore small enough to reject the null hypothesis. We can subsequently conclude that there IS an association between the prevalence of the swine flu and age.
```
